services:
  - type: web
    name: hirecheck-backend
    runtime: node
    rootDir: app
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JUDGE0_API
        sync: false
      - key: JUDGE0_KEY
        sync: false
